apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskboard.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql+psycopg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.database }}"
